"""Fictional Kazakhstan demo fixtures. No real contacts or hosted prototypes."""

TASKS = [
    dict(title="AI contract review for an Almaty distributor", industry="legal",
         context="An Almaty equipment distributor reviews supplier contracts manually.",
         need="Highlight payment terms and risky clauses for a human legal reviewer.",
         users="Legal staff and procurement managers at the distributor.",
         data=None, constraints=None, success_criteria=None,
         expected_result="A clause review screen with links to the original contract.",
         contact="legal@alatau-demo.example", interaction_format=None,
         confirmed_fields=["context", "need", "contact"]),
    dict(title="Early support for students at a Shymkent college", industry="education",
         context="College tutors struggle to identify students who need early support.",
         need="Help tutors prioritize supportive outreach using attendance trends.",
         users="College tutors and student support coordinators.",
         data="Attendance exports may be available; permission has not been agreed.",
         constraints=None, success_criteria=None,
         expected_result="A tutor dashboard that explains attendance changes without automatic decisions.",
         contact="tutors@shymkent-demo.example", interaction_format=None,
         confirmed_fields=["context", "need"]),
    dict(title="Predictive maintenance for a Karaganda workshop", industry="manufacturing",
         context="A Karaganda workshop loses production time when milling machines stop.",
         need="Identify unusual vibration patterns before maintenance incidents.",
         users="Maintenance engineers working on the milling production line.",
         data="Six months of timestamped sensor CSV files can be shared in a local folder.",
         constraints="The prototype must operate offline on the workshop laptop.",
         expected_result="A dashboard displaying machine trends and candidate maintenance alerts.",
         success_criteria=None, contact="engineer@saryarka-demo.example",
         interaction_format="Weekly feedback calls are proposed but the shift schedule is unresolved.",
         confirmed_fields=["context", "need", "data", "users", "contact"]),
    dict(title="Bilingual customer support for an Astana service desk", industry="services",
         context="A local service desk repeatedly answers the same Kazakh and Russian questions.",
         need="Draft answers from approved FAQs for staff to review before sending.",
         users="Customer support operators serving residents in two languages.",
         data="An approved bilingual FAQ spreadsheet is available for the student team.",
         constraints="Keep all personal customer information outside the demonstration dataset.",
         expected_result="A bilingual search and answer drafting interface with source links.",
         success_criteria="Resolve at least 80 percent of the agreed FAQ test questions.",
         contact="support@astana-demo.example", interaction_format=None,
         confirmed_fields=["context", "need", "expected_result", "users", "constraints", "contact"]),
    dict(title="Delivery route planning for a Shymkent wholesaler", industry="logistics",
         context="A Shymkent wholesaler plans daily shop deliveries using spreadsheets.",
         need="Compare route plans while respecting vehicle capacity and delivery windows.",
         users="Dispatchers and drivers making deliveries across the city.",
         data="Anonymized stop coordinates and delivery volumes are ready as CSV files.",
         constraints="Use existing vehicles and keep routes within agreed driver shift hours.",
         expected_result="An editable route map with distance and delivery-window summaries.",
         success_criteria="Reduce planned driving distance by 15 percent on the sample delivery days.",
         contact="dispatch@ontustik-demo.example", interaction_format=None,
         confirmed_fields=["context", "need", "data", "expected_result", "users", "contact"]),
    dict(title="Invoice document processing for an Aktobe supplier", industry="operations",
         context="An Aktobe supplier manually copies invoice lines into accounting spreadsheets.",
         need="Extract invoice fields and flag uncertain values for human checking.",
         users="Accounting assistants and the supplier finance manager.",
         data="Two hundred synthetic invoice scans and expected outputs are available locally.",
         constraints="Use synthetic records only and retain a human review step for every invoice.",
         expected_result="A document upload screen and a downloadable reviewed spreadsheet.",
         success_criteria="Match at least 90 percent of invoice totals in the held-out sample.",
         contact="finance@aktobe-demo.example", interaction_format=None,
         confirmed_fields=["context", "need", "data", "expected_result", "success_criteria", "contact"]),
    dict(title="Retail demand forecasting for Almaty neighborhood shops", industry="retail",
         context="An Almaty grocery cooperative has frequent stockouts and fresh produce waste.",
         need="Forecast weekly product demand to help store managers plan orders.",
         users="Store managers placing weekly orders for neighborhood shops.",
         data="Anonymized weekly sales and promotion CSV files are available in a shared folder.",
         constraints="Use only aggregate sales and deliver a prototype within four weeks.",
         expected_result="A product demand dashboard with downloadable order suggestions.",
         success_criteria="Reduce forecast error by 20 percent against the previous-week baseline.",
         contact="orders@almaty-demo.example",
         interaction_format="Weekly video reviews with two store managers and feedback by email.",
         confirmed_fields=["context", "need", "users", "data", "constraints", "expected_result", "success_criteria", "contact", "interaction_format"]),
    dict(title="Employee knowledge assistant for a Pavlodar plant", industry="manufacturing",
         context="New plant employees spend hours finding approved internal operating guidance.",
         need="Make approved manuals searchable with citations and human escalation options.",
         users="New employees and shift supervisors at the Pavlodar plant.",
         data="A curated set of nonconfidential training manuals is available as PDF files.",
         constraints="Only approved training content may appear; safety decisions remain with supervisors.",
         expected_result="A searchable manual library with page citations and feedback collection.",
         success_criteria="Find the correct source page for 90 percent of the agreed training questions.",
         contact="training@ertis-demo.example",
         interaction_format="Weekly review sessions with the training coordinator and two supervisors.",
         confirmed_fields=["context", "need", "users", "data", "constraints", "expected_result", "success_criteria", "contact", "interaction_format"]),
]

TEAMS = [
    dict(name="Alatau NLP Lab", interests="Legal documents, bilingual search", skills="Python, NLP, information retrieval", technologies="FastAPI, React, scikit-learn"),
    dict(name="Sana Student Analytics", interests="Education, student support, responsible analytics", skills="Data Analytics, Python, visualization", technologies="pandas, FastAPI, React"),
    dict(name="Saryarka Vision", interests="Industrial monitoring, document recognition", skills="Computer Vision, ML, time series", technologies="PyTorch, OpenCV, Python"),
    dict(name="Steppe Route Makers", interests="Logistics, optimization, retail", skills="Operations research, geospatial analysis, React", technologies="OR-Tools, FastAPI, Leaflet"),
    dict(name="Ertis Builders", interests="Enterprise tools, knowledge search, forecasting", skills="NLP, ML, full-stack development", technologies="Python, PostgreSQL, React, FastAPI"),
]

# Task index, team index, idea, plan, timeline, demo decision.
PROPOSALS = [
    (0, 0, "Clause extraction with a lawyer review queue", "Label sample clauses, build a rule baseline, and review errors with legal staff.", "Three weeks after sample contracts are approved", "pending"),
    (0, 4, "Contract comparison and source-linked search", "Compare document sections, surface changes, and test a reviewer interface.", "Four weeks with weekly review milestones", "pending"),
    (2, 2, "Sensor anomaly dashboard", "Profile vibration readings, fit a baseline, and replay known machine incidents.", "Four weeks including one workshop review", "accepted"),
    (3, 0, "Kazakh and Russian FAQ retrieval", "Clean FAQ pairs, implement search, and evaluate draft answers with operators.", "Two weeks for a bilingual demo", "pending"),
    (4, 3, "Capacity-aware delivery routing", "Import stops, solve a capacity baseline, and compare route distances on a map.", "Three weeks for dispatcher testing", "accepted"),
    (4, 4, "Dispatcher-assisted route comparison", "Build a map editor and compare manual plans with simple route heuristics.", "Two weeks for the first route editor", "accepted"),
    (5, 2, "Invoice OCR with confidence review", "Extract invoice totals, highlight uncertain fields, and export reviewed rows.", "Three weeks using synthetic invoice samples", "rejected"),
    (6, 1, "Store-level seasonal demand baseline", "Audit weekly sales, backtest seasonal averages, and visualize reorder estimates.", "Four weeks with a baseline after week one", "pending"),
    (6, 4, "Promotion-aware product forecasts", "Join promotions to sales, compare simple models, and display forecast errors.", "Four weeks with manager feedback every Friday", "accepted"),
]
