"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, ApiError, type Challenge, type Score } from "@/lib/api";
import { ReadinessBadge, ReadinessScore, ScoreBreakdown } from "./readiness";
import { ErrorState, LoadingState } from "./states";
const fields = [["context", "Business context"], ["need", "Business need"], ["users", "Who this helps"], ["data", "Available data & materials"], ["expected_result", "Expected result"], ["success_criteria", "Success criteria"], ["constraints", "Constraints"], ["contact", "Business contact"], ["interaction_format", "Working with the business"]] as const;
export function ChallengeDetail({ id }: { id: string }) {
  const [task, setTask] = useState<Challenge | null>(null);
  const [score, setScore] = useState<Score | null>(null);
  const [status, setStatus] = useState("loading");
  const [attempt, setAttempt] = useState(0);
  useEffect(() => {
    const controller = new AbortController(); setStatus("loading"); setScore(null);
    api.challenge(id, controller.signal).then(async task => {
      const result = await api.score(id, controller.signal).catch(() => null);
      if (!controller.signal.aborted) { setTask(task); setScore(result); setStatus("ready"); }
    }).catch(error => { if (!controller.signal.aborted) setStatus(error instanceof ApiError && error.status === 404 ? "missing" : "error"); });
    return () => controller.abort();
  }, [id, attempt]);
  if (status === "loading") return <LoadingState />;
  if (status !== "ready" || !task) return <ErrorState notFound={status === "missing"} retry={() => setAttempt(a => a + 1)} />;
  return <><Link href="/" className="back-link">← All challenges</Link><header className="detail-header"><span className="industry">{task.industry || "Industry not specified"}</span><h1>{task.title || "Untitled challenge"}</h1><div className="flex items-center gap-4"><ReadinessBadge level={task.readiness_level} /><span className="muted text-sm">Published business challenge</span></div><div className="challenge-actions"><Link className="button" href={`/challenges/${id}/propose`}>Submit proposal</Link><Link href={`/business/challenges/${id}/proposals`}>Review proposals as business →</Link></div></header>
    <div className="detail-layout"><div className="brief"><div className="section-heading"><h2>The challenge brief</h2><span className="muted text-sm">{task.confirmed_fields.length} fields confirmed</span></div>{fields.map(([key, label]) => <section className="brief-field" key={key}><div className="field-heading"><h3>{label}</h3>{task[key]?.trim() && <span className={task.confirmed_fields.includes(key) ? "confirmed-label" : "unconfirmed-label"}>{task.confirmed_fields.includes(key) ? "✓ Business confirmed" : "Not confirmed yet"}</span>}</div><p className={!task[key]?.trim() ? "unknown" : ""}>{task[key]?.trim() || "Not confirmed yet — the business has not provided this information."}</p></section>)}</div>
      <aside className="readiness-panel"><div className="eyebrow">CHALLENGE READINESS</div><ReadinessScore score={task.score} level={task.readiness_level} /><ReadinessBadge level={task.readiness_level} /><p className="panel-description">Based on information confirmed by the business. This describes the brief’s completeness, not the value of the idea.</p><hr /><h2>What’s behind the score</h2>{score ? <ScoreBreakdown result={score} /> : <p role="status" className="unknown">The detailed breakdown is temporarily unavailable.<button className="text-button" onClick={() => setAttempt(a => a + 1)}>Try again</button></p>}<div className="score-note">Calculated using transparent rules.<br />Never generated by AI.</div></aside>
    </div></>;
}
