import { test, expect } from "@playwright/test";

const backend = "http://127.0.0.1:8000";

test("golden flow runs entirely in UI: interview, confirmation, blockers, publish, proposal, decision, unpublish", async ({ page, request }) => {
  const title = "UI golden contract review";
  const writes: string[] = [];
  page.on("request", req => { if (req.method() === "POST") writes.push(new URL(req.url()).pathname); });
  await page.goto("/business");
  await page.getByRole("link", { name: "New challenge", exact: true }).click();
  await page.getByLabel("Working title").fill(title);
  await page.getByLabel("Your description", { exact: true }).fill("Our employees spend too much time reviewing contracts.\nWe want to automate this process.");
  await expect(page.getByRole("button", { name: "Start interview", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Start interview", exact: true }).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); });
  await expect(page).toHaveURL(/\/business\/challenges\/\d+\/interview$/);
  const id = page.url().split("/").at(-2)!;
  expect(writes.filter(path => path === "/api/tasks")).toHaveLength(1);
  expect(writes.filter(path => path.endsWith("/interview/start"))).toHaveLength(1);
  const need = page.getByTestId("interview-question-need");
  await need.locator("textarea").fill("We need to identify clauses that differ from our approved contract template.");
  await expect(need.getByRole("button", { name: "Answer", exact: true })).toBeEnabled();
  await need.getByRole("button", { name: "Answer", exact: true }).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); });
  await expect(page.getByTestId("knowledge-need")).toContainText("approved contract template");
  await page.reload();
  const users = page.getByTestId("interview-question-users");
  await users.getByRole("button", { name: "I don't understand", exact: true }).click();
  await expect(users).toContainText("Who experiences this problem?");
  await page.getByTestId("interview-question-users").getByRole("button", { name: "I don't know", exact: true }).click();
  await expect(page.getByTestId("knowledge-users")).toContainText("Unknown");
  await page.reload();
  await expect(page.getByTestId("knowledge-users")).toContainText("Unknown");
  const data = page.getByTestId("interview-question-data");
  await data.getByRole("button", { name: "Needs another expert", exact: true }).click();
  await data.getByLabel("Expert name or role").fill("IT department");
  await data.getByRole("button", { name: "Mark needs expert" }).click();
  await expect(page.getByTestId("knowledge-data")).toContainText("IT department");
  await page.reload();
  await expect(page.getByTestId("knowledge-data")).toContainText("IT department");
  const review = page.getByTestId("review-need");
  await review.getByRole("button", { name: "Save reviewed value" }).click();
  await expect(review.getByRole("button", { name: "Confirm field", exact: true })).toBeEnabled();
  await review.getByRole("button", { name: "Confirm field", exact: true }).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); });
  await expect(review.getByRole("button", { name: "Confirmed", exact: true })).toBeVisible();
  const publication = page.getByTestId("publication");
  await expect(publication).toContainText("Readiness: 10/100");
  await expect(publication).toContainText("users (unknown)");
  await expect(publication).toContainText("data (needs expert)");
  await expect(page.getByRole("button", { name: "Run execution test", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Run execution test", exact: true }).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); });
  await expect(publication).toContainText(/Execution blockers: [1-9]/);
  const before = await (await request.get(`${backend}/api/tasks/${id}`)).json();
  const previousTest = await (await request.get(`${backend}/api/tasks/${id}/stress-test`)).json();
  expect(writes.filter(path => path.endsWith("/interview/respond"))).toHaveLength(4);
  expect(writes.filter(path => path.endsWith("/confirm"))).toHaveLength(1);
  expect(writes.filter(path => path.endsWith("/stress-test"))).toHaveLength(1);
  let aiWrites = 0;
  page.on("request", req => { if (req.method() === "POST" && /\/(stress-test|interview\/)/.test(req.url())) aiWrites++; });
  await expect(publication.getByRole("button", { name: "Publish challenge", exact: true })).toBeEnabled();
  await publication.getByRole("button", { name: "Publish challenge", exact: true }).evaluate((button: HTMLButtonElement) => { button.click(); button.click(); });
  await expect(page.getByRole("status").filter({ hasText: /^Challenge published$/ })).toBeVisible();
  await expect(publication.getByRole("heading", { name: "Published", exact: true })).toBeVisible();
  await expect(publication).toContainText("Readiness: 10/100");
  await page.reload();
  await expect(publication.getByRole("heading", { name: "Published", exact: true })).toBeVisible();
  const after = await (await request.get(`${backend}/api/tasks/${id}`)).json();
  expect(writes.filter(path => path.endsWith("/publish"))).toHaveLength(1);
  expect(after).toEqual({ ...before, published: true });
  expect(await (await request.get(`${backend}/api/tasks/${id}/stress-test`)).json()).toEqual(previousTest);
  expect(aiWrites).toBe(0);
  await publication.screenshot({ path: "test-results/publication.png" });
  await publication.getByRole("link", { name: "View in catalog", exact: true }).click();
  await expect(page).toHaveURL(`http://localhost:3000/challenges/${id}`);
  await expect(page.getByRole("heading", { name: title, exact: true })).toBeVisible();
  await page.getByLabel("Demo role").selectOption("student");
  await page.getByTestId("challenge-card").filter({ has: page.getByRole("heading", { name: title, exact: true }) }).click();
  await page.getByRole("link", { name: "Submit proposal", exact: true }).click();
  await page.getByLabel("Team", { exact: true }).selectOption({ label: "Alatau NLP Lab" });
  await page.getByLabel("Solution idea", { exact: true }).fill("Compare supplied clauses with the approved template.");
  await page.getByLabel("Implementation plan", { exact: true }).fill("Review supplied examples and demonstrate comparisons to the business.");
  await page.getByLabel("Timeline", { exact: true }).fill("Two weeks");
  await page.getByLabel("Prototype URL", { exact: true }).fill("https://example.com/contract-demo");
  await page.getByRole("button", { name: "Submit proposal", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Proposal submitted" })).toBeVisible();
  await page.getByLabel("Demo role").selectOption("business");
  await page.locator(".business-row").filter({ hasText: title }).getByRole("link", { name: "Review proposals", exact: true }).click();
  await page.getByRole("button", { name: "Accept", exact: true }).click();
  await expect(page.locator(".proposal-review").getByRole("status")).toHaveText("Accepted");
  await page.reload();
  await expect(page.locator(".proposal-review").getByRole("status")).toHaveText("Accepted");
  await page.getByRole("button", { name: "Reject", exact: true }).click();
  await expect(page.locator(".proposal-review").getByRole("status")).toHaveText("Rejected");
  await page.getByRole("link", { name: /Business workspace/ }).click();
  await page.locator(".business-row").filter({ hasText: title }).getByRole("link", { name: "Clarify challenge" }).click();
  await publication.getByRole("button", { name: "Unpublish", exact: true }).click();
  await expect(publication.getByRole("button", { name: "Publish challenge", exact: true })).toBeVisible();
  await expect(publication.getByRole("link", { name: "View in catalog" })).toHaveCount(0);
  expect(await (await request.get(`${backend}/api/tasks/${id}`)).json()).toEqual(before);
  expect((await request.get(`${backend}/api/catalog/${id}`)).status()).toBe(404);
  expect(await (await request.get(`${backend}/api/tasks/${id}/stress-test`)).json()).toEqual(previousTest);
  expect(aiWrites).toBe(0);
});

test("missing title and need errors are useful and repairable; zero readiness can publish", async ({ page, request }) => {
  const task = await (await request.post(`${backend}/api/tasks`, { data: { context: "Employees review supplier contracts." } })).json();
  await page.goto(`/business/challenges/${task.id}/interview`);
  const panel = page.getByTestId("publication");
  await panel.getByRole("button", { name: "Publish challenge" }).click();
  await expect(page.locator(".form-error[role=alert]")).toContainText("A saved, nonblank title and business need are required");
  expect((await (await request.get(`${backend}/api/tasks/${task.id}`)).json()).title).toBeNull();
  await panel.getByLabel("Challenge title").fill("Zero score publication");
  await panel.getByRole("button", { name: "Save title" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Challenge title saved" })).toBeVisible();
  await panel.getByRole("button", { name: "Publish challenge" }).click();
  await expect(page.locator(".form-error[role=alert]")).toContainText("business need");
  const review = page.getByTestId("review-need");
  await review.locator("textarea").fill("Identify clauses that differ from the approved contract template.");
  await review.getByRole("button", { name: "Save reviewed value" }).click();
  await expect(page.getByRole("status").filter({ hasText: "Reviewed value saved" })).toBeVisible();
  await panel.getByRole("button", { name: "Publish challenge" }).click();
  await expect(panel.getByRole("link", { name: "View in catalog" })).toBeVisible();
  await expect(panel).toContainText("Readiness: 0/100");
  const saved = await (await request.get(`${backend}/api/tasks/${task.id}`)).json();
  expect(saved.confirmed_fields).toEqual([]);
  expect(saved.published).toBe(true);
  expect((await (await request.get(`${backend}/api/tasks/${task.id}/stress-test`)).json()).result).toBeNull();
});

test("stale blockers are not presented as current and publication failure is retryable", async ({ page, request }) => {
  const task = await (await request.post(`${backend}/api/tasks`, { data: { title: "Publication recovery", context: "Employees review supplier contracts.", need: "Compare supplier clauses with our approved contract template." } })).json();
  await page.goto(`/business/challenges/${task.id}/interview`);
  await page.getByRole("button", { name: "Run execution test", exact: true }).click();
  const panel = page.getByTestId("publication");
  await expect(panel).toContainText(/Execution blockers: [1-9]/);
  const review = page.getByTestId("review-need");
  await review.locator("textarea").fill("Compare the payment clauses with the business-approved template.");
  await review.getByRole("button", { name: "Save reviewed value" }).click();
  await expect(page.getByTestId("execution-test")).toContainText("Challenge information changed since this test.");
  await expect(panel).toContainText("No current verified execution blocker count available");
  await panel.getByLabel("Challenge title").fill("Unsaved title stays here");
  await page.route(`**/api/tasks/${task.id}/publish`, route => route.fulfill({ status: 503, contentType: "application/json", body: '{}' }));
  await panel.getByRole("button", { name: "Publish challenge" }).click();
  await expect(page.locator(".form-error[role=alert]")).toContainText("We couldn't confirm the latest change");
  await expect(panel.getByRole("button", { name: "Publish challenge" })).toBeEnabled();
  await expect(panel.getByLabel("Challenge title")).toHaveValue("Unsaved title stays here");
  await page.unroute(`**/api/tasks/${task.id}/publish`);
  await panel.getByRole("button", { name: "Publish challenge" }).click();
  await expect(panel.getByRole("link", { name: "View in catalog" })).toBeVisible();
});
